### ISSUE TITLE
Define the scope of BaseTest class in the framework

### ISSUE THREAD

**Issue by tkvarma-tw** [dsahu-tw/UIAutomation#2]
The BaseTest class is always defined as the class which contains different webelements and its methods which can common in all the pages of the product (Ex: settings,Logo icons,logout button, navigation bar etc).

In this framework, we have added the webelements operations like click, getText etc as part of BaseTest class which can be changed by putting the operations methods in separate operations folder and using Interface with different operations as separate class like click,getText etc. This will make the code readability more easily and adding the new operations will be easy by adding different classes.

**Comment by dsahu-tw** [comment]
It would be better if we move common functions to BasePage instead of BaseTest class to follow the POM model. 

For example, isElementPresent() is a common function.
If we keep it in BaseTest then while calling it from test case, locator needs to pass, whereas we are keeping our framework to validate/action all things on the related page only. So we can write isElementPresnet() in BasePage and create a method in the related page to verify the same.
